/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BorrowRouteImport } from './routes/borrow'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as RunesInfoRouteImport } from './routes/runes-info'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as YourTxsRouteImport } from './routes/your-txs'
import { Route as ApiBtcPriceRouteImport } from './routes/api.btc-price'
import { Route as ApiPopularRunesRouteImport } from './routes/api.popular-runes'
import { Route as ApiPortfolioDataRouteImport } from './routes/api.portfolio-data'
import { Route as ApiRunePriceHistoryRouteImport } from './routes/api.rune-price-history'
import { Route as ApiLiquidiumAuthRouteImport } from './routes/api.liquidium.auth'
import { Route as ApiLiquidiumChallengeRouteImport } from './routes/api.liquidium.challenge'
import { Route as ApiLiquidiumPortfolioRouteImport } from './routes/api.liquidium.portfolio'
import { Route as ApiLiquidiumRepayRouteImport } from './routes/api.liquidium.repay'
import { Route as ApiOrdiscanBtcBalanceRouteImport } from './routes/api.ordiscan.btc-balance'
import { Route as ApiOrdiscanListRunesRouteImport } from './routes/api.ordiscan.list-runes'
import { Route as ApiOrdiscanRuneActivityRouteImport } from './routes/api.ordiscan.rune-activity'
import { Route as ApiOrdiscanRuneBalancesRouteImport } from './routes/api.ordiscan.rune-balances'
import { Route as ApiOrdiscanRuneInfoRouteImport } from './routes/api.ordiscan.rune-info'
import { Route as ApiOrdiscanRuneInfoByIdRouteImport } from './routes/api.ordiscan.rune-info-by-id'
import { Route as ApiOrdiscanRuneMarketRouteImport } from './routes/api.ordiscan.rune-market'
import { Route as ApiOrdiscanRuneUpdateRouteImport } from './routes/api.ordiscan.rune-update'
import { Route as ApiSatsTerminalQuoteRouteImport } from './routes/api.sats-terminal.quote'
import { Route as ApiSatsTerminalSearchRouteImport } from './routes/api.sats-terminal.search'
import { Route as ApiLiquidiumBorrowPrepareRouteImport } from './routes/api.liquidium.borrow.prepare'
import { Route as ApiLiquidiumBorrowQuotesRouteImport } from './routes/api.liquidium.borrow.quotes'
import { Route as ApiLiquidiumBorrowRangesRouteImport } from './routes/api.liquidium.borrow.ranges'
import { Route as ApiLiquidiumBorrowSubmitRouteImport } from './routes/api.liquidium.borrow.submit'
import { Route as ApiSatsTerminalPsbtConfirmRouteImport } from './routes/api.sats-terminal.psbt.confirm'
import { Route as ApiSatsTerminalPsbtCreateRouteImport } from './routes/api.sats-terminal.psbt.create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrowRoute = BorrowRouteImport.update({
  id: '/borrow',
  path: '/borrow',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RunesInfoRoute = RunesInfoRouteImport.update({
  id: '/runes-info',
  path: '/runes-info',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const YourTxsRoute = YourTxsRouteImport.update({
  id: '/your-txs',
  path: '/your-txs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBtcPriceRoute = ApiBtcPriceRouteImport.update({
  id: '/api/btc-price',
  path: '/api/btc-price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPopularRunesRoute = ApiPopularRunesRouteImport.update({
  id: '/api/popular-runes',
  path: '/api/popular-runes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioDataRoute = ApiPortfolioDataRouteImport.update({
  id: '/api/portfolio-data',
  path: '/api/portfolio-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunePriceHistoryRoute = ApiRunePriceHistoryRouteImport.update({
  id: '/api/rune-price-history',
  path: '/api/rune-price-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiquidiumAuthRoute = ApiLiquidiumAuthRouteImport.update({
  id: '/api/liquidium/auth',
  path: '/api/liquidium/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiquidiumChallengeRoute = ApiLiquidiumChallengeRouteImport.update({
  id: '/api/liquidium/challenge',
  path: '/api/liquidium/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiquidiumPortfolioRoute = ApiLiquidiumPortfolioRouteImport.update({
  id: '/api/liquidium/portfolio',
  path: '/api/liquidium/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiquidiumRepayRoute = ApiLiquidiumRepayRouteImport.update({
  id: '/api/liquidium/repay',
  path: '/api/liquidium/repay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdiscanBtcBalanceRoute = ApiOrdiscanBtcBalanceRouteImport.update({
  id: '/api/ordiscan/btc-balance',
  path: '/api/ordiscan/btc-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdiscanListRunesRoute = ApiOrdiscanListRunesRouteImport.update({
  id: '/api/ordiscan/list-runes',
  path: '/api/ordiscan/list-runes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdiscanRuneActivityRoute = ApiOrdiscanRuneActivityRouteImport.update({
  id: '/api/ordiscan/rune-activity',
  path: '/api/ordiscan/rune-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdiscanRuneBalancesRoute = ApiOrdiscanRuneBalancesRouteImport.update({
  id: '/api/ordiscan/rune-balances',
  path: '/api/ordiscan/rune-balances',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdiscanRuneInfoRoute = ApiOrdiscanRuneInfoRouteImport.update({
  id: '/api/ordiscan/rune-info',
  path: '/api/ordiscan/rune-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdiscanRuneInfoByIdRoute = ApiOrdiscanRuneInfoByIdRouteImport.update({
  id: '/api/ordiscan/rune-info-by-id',
  path: '/api/ordiscan/rune-info-by-id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdiscanRuneMarketRoute = ApiOrdiscanRuneMarketRouteImport.update({
  id: '/api/ordiscan/rune-market',
  path: '/api/ordiscan/rune-market',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdiscanRuneUpdateRoute = ApiOrdiscanRuneUpdateRouteImport.update({
  id: '/api/ordiscan/rune-update',
  path: '/api/ordiscan/rune-update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSatsTerminalQuoteRoute = ApiSatsTerminalQuoteRouteImport.update({
  id: '/api/sats-terminal/quote',
  path: '/api/sats-terminal/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSatsTerminalSearchRoute = ApiSatsTerminalSearchRouteImport.update({
  id: '/api/sats-terminal/search',
  path: '/api/sats-terminal/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiquidiumBorrowPrepareRoute =
  ApiLiquidiumBorrowPrepareRouteImport.update({
    id: '/api/liquidium/borrow/prepare',
    path: '/api/liquidium/borrow/prepare',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLiquidiumBorrowQuotesRoute =
  ApiLiquidiumBorrowQuotesRouteImport.update({
    id: '/api/liquidium/borrow/quotes',
    path: '/api/liquidium/borrow/quotes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLiquidiumBorrowRangesRoute =
  ApiLiquidiumBorrowRangesRouteImport.update({
    id: '/api/liquidium/borrow/ranges',
    path: '/api/liquidium/borrow/ranges',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLiquidiumBorrowSubmitRoute =
  ApiLiquidiumBorrowSubmitRouteImport.update({
    id: '/api/liquidium/borrow/submit',
    path: '/api/liquidium/borrow/submit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSatsTerminalPsbtConfirmRoute =
  ApiSatsTerminalPsbtConfirmRouteImport.update({
    id: '/api/sats-terminal/psbt/confirm',
    path: '/api/sats-terminal/psbt/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSatsTerminalPsbtCreateRoute =
  ApiSatsTerminalPsbtCreateRouteImport.update({
    id: '/api/sats-terminal/psbt/create',
    path: '/api/sats-terminal/psbt/create',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/borrow': typeof BorrowRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRoute
  '/legal': typeof LegalRoute
  '/portfolio': typeof PortfolioRoute
  '/runes-info': typeof RunesInfoRoute
  '/swap': typeof SwapRoute
  '/your-txs': typeof YourTxsRoute
  '/api/btc-price': typeof ApiBtcPriceRoute
  '/api/popular-runes': typeof ApiPopularRunesRoute
  '/api/portfolio-data': typeof ApiPortfolioDataRoute
  '/api/rune-price-history': typeof ApiRunePriceHistoryRoute
  '/api/liquidium/auth': typeof ApiLiquidiumAuthRoute
  '/api/liquidium/challenge': typeof ApiLiquidiumChallengeRoute
  '/api/liquidium/portfolio': typeof ApiLiquidiumPortfolioRoute
  '/api/liquidium/repay': typeof ApiLiquidiumRepayRoute
  '/api/ordiscan/btc-balance': typeof ApiOrdiscanBtcBalanceRoute
  '/api/ordiscan/list-runes': typeof ApiOrdiscanListRunesRoute
  '/api/ordiscan/rune-activity': typeof ApiOrdiscanRuneActivityRoute
  '/api/ordiscan/rune-balances': typeof ApiOrdiscanRuneBalancesRoute
  '/api/ordiscan/rune-info': typeof ApiOrdiscanRuneInfoRoute
  '/api/ordiscan/rune-info-by-id': typeof ApiOrdiscanRuneInfoByIdRoute
  '/api/ordiscan/rune-market': typeof ApiOrdiscanRuneMarketRoute
  '/api/ordiscan/rune-update': typeof ApiOrdiscanRuneUpdateRoute
  '/api/sats-terminal/quote': typeof ApiSatsTerminalQuoteRoute
  '/api/sats-terminal/search': typeof ApiSatsTerminalSearchRoute
  '/api/liquidium/borrow/prepare': typeof ApiLiquidiumBorrowPrepareRoute
  '/api/liquidium/borrow/quotes': typeof ApiLiquidiumBorrowQuotesRoute
  '/api/liquidium/borrow/ranges': typeof ApiLiquidiumBorrowRangesRoute
  '/api/liquidium/borrow/submit': typeof ApiLiquidiumBorrowSubmitRoute
  '/api/sats-terminal/psbt/confirm': typeof ApiSatsTerminalPsbtConfirmRoute
  '/api/sats-terminal/psbt/create': typeof ApiSatsTerminalPsbtCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/borrow': typeof BorrowRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRoute
  '/legal': typeof LegalRoute
  '/portfolio': typeof PortfolioRoute
  '/runes-info': typeof RunesInfoRoute
  '/swap': typeof SwapRoute
  '/your-txs': typeof YourTxsRoute
  '/api/btc-price': typeof ApiBtcPriceRoute
  '/api/popular-runes': typeof ApiPopularRunesRoute
  '/api/portfolio-data': typeof ApiPortfolioDataRoute
  '/api/rune-price-history': typeof ApiRunePriceHistoryRoute
  '/api/liquidium/auth': typeof ApiLiquidiumAuthRoute
  '/api/liquidium/challenge': typeof ApiLiquidiumChallengeRoute
  '/api/liquidium/portfolio': typeof ApiLiquidiumPortfolioRoute
  '/api/liquidium/repay': typeof ApiLiquidiumRepayRoute
  '/api/ordiscan/btc-balance': typeof ApiOrdiscanBtcBalanceRoute
  '/api/ordiscan/list-runes': typeof ApiOrdiscanListRunesRoute
  '/api/ordiscan/rune-activity': typeof ApiOrdiscanRuneActivityRoute
  '/api/ordiscan/rune-balances': typeof ApiOrdiscanRuneBalancesRoute
  '/api/ordiscan/rune-info': typeof ApiOrdiscanRuneInfoRoute
  '/api/ordiscan/rune-info-by-id': typeof ApiOrdiscanRuneInfoByIdRoute
  '/api/ordiscan/rune-market': typeof ApiOrdiscanRuneMarketRoute
  '/api/ordiscan/rune-update': typeof ApiOrdiscanRuneUpdateRoute
  '/api/sats-terminal/quote': typeof ApiSatsTerminalQuoteRoute
  '/api/sats-terminal/search': typeof ApiSatsTerminalSearchRoute
  '/api/liquidium/borrow/prepare': typeof ApiLiquidiumBorrowPrepareRoute
  '/api/liquidium/borrow/quotes': typeof ApiLiquidiumBorrowQuotesRoute
  '/api/liquidium/borrow/ranges': typeof ApiLiquidiumBorrowRangesRoute
  '/api/liquidium/borrow/submit': typeof ApiLiquidiumBorrowSubmitRoute
  '/api/sats-terminal/psbt/confirm': typeof ApiSatsTerminalPsbtConfirmRoute
  '/api/sats-terminal/psbt/create': typeof ApiSatsTerminalPsbtCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/borrow': typeof BorrowRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRoute
  '/legal': typeof LegalRoute
  '/portfolio': typeof PortfolioRoute
  '/runes-info': typeof RunesInfoRoute
  '/swap': typeof SwapRoute
  '/your-txs': typeof YourTxsRoute
  '/api/btc-price': typeof ApiBtcPriceRoute
  '/api/popular-runes': typeof ApiPopularRunesRoute
  '/api/portfolio-data': typeof ApiPortfolioDataRoute
  '/api/rune-price-history': typeof ApiRunePriceHistoryRoute
  '/api/liquidium/auth': typeof ApiLiquidiumAuthRoute
  '/api/liquidium/challenge': typeof ApiLiquidiumChallengeRoute
  '/api/liquidium/portfolio': typeof ApiLiquidiumPortfolioRoute
  '/api/liquidium/repay': typeof ApiLiquidiumRepayRoute
  '/api/ordiscan/btc-balance': typeof ApiOrdiscanBtcBalanceRoute
  '/api/ordiscan/list-runes': typeof ApiOrdiscanListRunesRoute
  '/api/ordiscan/rune-activity': typeof ApiOrdiscanRuneActivityRoute
  '/api/ordiscan/rune-balances': typeof ApiOrdiscanRuneBalancesRoute
  '/api/ordiscan/rune-info': typeof ApiOrdiscanRuneInfoRoute
  '/api/ordiscan/rune-info-by-id': typeof ApiOrdiscanRuneInfoByIdRoute
  '/api/ordiscan/rune-market': typeof ApiOrdiscanRuneMarketRoute
  '/api/ordiscan/rune-update': typeof ApiOrdiscanRuneUpdateRoute
  '/api/sats-terminal/quote': typeof ApiSatsTerminalQuoteRoute
  '/api/sats-terminal/search': typeof ApiSatsTerminalSearchRoute
  '/api/liquidium/borrow/prepare': typeof ApiLiquidiumBorrowPrepareRoute
  '/api/liquidium/borrow/quotes': typeof ApiLiquidiumBorrowQuotesRoute
  '/api/liquidium/borrow/ranges': typeof ApiLiquidiumBorrowRangesRoute
  '/api/liquidium/borrow/submit': typeof ApiLiquidiumBorrowSubmitRoute
  '/api/sats-terminal/psbt/confirm': typeof ApiSatsTerminalPsbtConfirmRoute
  '/api/sats-terminal/psbt/create': typeof ApiSatsTerminalPsbtCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/borrow'
    | '/changelog'
    | '/docs'
    | '/legal'
    | '/portfolio'
    | '/runes-info'
    | '/swap'
    | '/your-txs'
    | '/api/btc-price'
    | '/api/popular-runes'
    | '/api/portfolio-data'
    | '/api/rune-price-history'
    | '/api/liquidium/auth'
    | '/api/liquidium/challenge'
    | '/api/liquidium/portfolio'
    | '/api/liquidium/repay'
    | '/api/ordiscan/btc-balance'
    | '/api/ordiscan/list-runes'
    | '/api/ordiscan/rune-activity'
    | '/api/ordiscan/rune-balances'
    | '/api/ordiscan/rune-info'
    | '/api/ordiscan/rune-info-by-id'
    | '/api/ordiscan/rune-market'
    | '/api/ordiscan/rune-update'
    | '/api/sats-terminal/quote'
    | '/api/sats-terminal/search'
    | '/api/liquidium/borrow/prepare'
    | '/api/liquidium/borrow/quotes'
    | '/api/liquidium/borrow/ranges'
    | '/api/liquidium/borrow/submit'
    | '/api/sats-terminal/psbt/confirm'
    | '/api/sats-terminal/psbt/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/borrow'
    | '/changelog'
    | '/docs'
    | '/legal'
    | '/portfolio'
    | '/runes-info'
    | '/swap'
    | '/your-txs'
    | '/api/btc-price'
    | '/api/popular-runes'
    | '/api/portfolio-data'
    | '/api/rune-price-history'
    | '/api/liquidium/auth'
    | '/api/liquidium/challenge'
    | '/api/liquidium/portfolio'
    | '/api/liquidium/repay'
    | '/api/ordiscan/btc-balance'
    | '/api/ordiscan/list-runes'
    | '/api/ordiscan/rune-activity'
    | '/api/ordiscan/rune-balances'
    | '/api/ordiscan/rune-info'
    | '/api/ordiscan/rune-info-by-id'
    | '/api/ordiscan/rune-market'
    | '/api/ordiscan/rune-update'
    | '/api/sats-terminal/quote'
    | '/api/sats-terminal/search'
    | '/api/liquidium/borrow/prepare'
    | '/api/liquidium/borrow/quotes'
    | '/api/liquidium/borrow/ranges'
    | '/api/liquidium/borrow/submit'
    | '/api/sats-terminal/psbt/confirm'
    | '/api/sats-terminal/psbt/create'
  id:
    | '__root__'
    | '/'
    | '/borrow'
    | '/changelog'
    | '/docs'
    | '/legal'
    | '/portfolio'
    | '/runes-info'
    | '/swap'
    | '/your-txs'
    | '/api/btc-price'
    | '/api/popular-runes'
    | '/api/portfolio-data'
    | '/api/rune-price-history'
    | '/api/liquidium/auth'
    | '/api/liquidium/challenge'
    | '/api/liquidium/portfolio'
    | '/api/liquidium/repay'
    | '/api/ordiscan/btc-balance'
    | '/api/ordiscan/list-runes'
    | '/api/ordiscan/rune-activity'
    | '/api/ordiscan/rune-balances'
    | '/api/ordiscan/rune-info'
    | '/api/ordiscan/rune-info-by-id'
    | '/api/ordiscan/rune-market'
    | '/api/ordiscan/rune-update'
    | '/api/sats-terminal/quote'
    | '/api/sats-terminal/search'
    | '/api/liquidium/borrow/prepare'
    | '/api/liquidium/borrow/quotes'
    | '/api/liquidium/borrow/ranges'
    | '/api/liquidium/borrow/submit'
    | '/api/sats-terminal/psbt/confirm'
    | '/api/sats-terminal/psbt/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BorrowRoute: typeof BorrowRoute
  ChangelogRoute: typeof ChangelogRoute
  DocsRoute: typeof DocsRoute
  LegalRoute: typeof LegalRoute
  PortfolioRoute: typeof PortfolioRoute
  RunesInfoRoute: typeof RunesInfoRoute
  SwapRoute: typeof SwapRoute
  YourTxsRoute: typeof YourTxsRoute
  ApiBtcPriceRoute: typeof ApiBtcPriceRoute
  ApiPopularRunesRoute: typeof ApiPopularRunesRoute
  ApiPortfolioDataRoute: typeof ApiPortfolioDataRoute
  ApiRunePriceHistoryRoute: typeof ApiRunePriceHistoryRoute
  ApiLiquidiumAuthRoute: typeof ApiLiquidiumAuthRoute
  ApiLiquidiumChallengeRoute: typeof ApiLiquidiumChallengeRoute
  ApiLiquidiumPortfolioRoute: typeof ApiLiquidiumPortfolioRoute
  ApiLiquidiumRepayRoute: typeof ApiLiquidiumRepayRoute
  ApiOrdiscanBtcBalanceRoute: typeof ApiOrdiscanBtcBalanceRoute
  ApiOrdiscanListRunesRoute: typeof ApiOrdiscanListRunesRoute
  ApiOrdiscanRuneActivityRoute: typeof ApiOrdiscanRuneActivityRoute
  ApiOrdiscanRuneBalancesRoute: typeof ApiOrdiscanRuneBalancesRoute
  ApiOrdiscanRuneInfoRoute: typeof ApiOrdiscanRuneInfoRoute
  ApiOrdiscanRuneInfoByIdRoute: typeof ApiOrdiscanRuneInfoByIdRoute
  ApiOrdiscanRuneMarketRoute: typeof ApiOrdiscanRuneMarketRoute
  ApiOrdiscanRuneUpdateRoute: typeof ApiOrdiscanRuneUpdateRoute
  ApiSatsTerminalQuoteRoute: typeof ApiSatsTerminalQuoteRoute
  ApiSatsTerminalSearchRoute: typeof ApiSatsTerminalSearchRoute
  ApiLiquidiumBorrowPrepareRoute: typeof ApiLiquidiumBorrowPrepareRoute
  ApiLiquidiumBorrowQuotesRoute: typeof ApiLiquidiumBorrowQuotesRoute
  ApiLiquidiumBorrowRangesRoute: typeof ApiLiquidiumBorrowRangesRoute
  ApiLiquidiumBorrowSubmitRoute: typeof ApiLiquidiumBorrowSubmitRoute
  ApiSatsTerminalPsbtConfirmRoute: typeof ApiSatsTerminalPsbtConfirmRoute
  ApiSatsTerminalPsbtCreateRoute: typeof ApiSatsTerminalPsbtCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrow': {
      id: '/borrow'
      path: '/borrow'
      fullPath: '/borrow'
      preLoaderRoute: typeof BorrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runes-info': {
      id: '/runes-info'
      path: '/runes-info'
      fullPath: '/runes-info'
      preLoaderRoute: typeof RunesInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/your-txs': {
      id: '/your-txs'
      path: '/your-txs'
      fullPath: '/your-txs'
      preLoaderRoute: typeof YourTxsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/btc-price': {
      id: '/api/btc-price'
      path: '/api/btc-price'
      fullPath: '/api/btc-price'
      preLoaderRoute: typeof ApiBtcPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/popular-runes': {
      id: '/api/popular-runes'
      path: '/api/popular-runes'
      fullPath: '/api/popular-runes'
      preLoaderRoute: typeof ApiPopularRunesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio-data': {
      id: '/api/portfolio-data'
      path: '/api/portfolio-data'
      fullPath: '/api/portfolio-data'
      preLoaderRoute: typeof ApiPortfolioDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rune-price-history': {
      id: '/api/rune-price-history'
      path: '/api/rune-price-history'
      fullPath: '/api/rune-price-history'
      preLoaderRoute: typeof ApiRunePriceHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/liquidium/auth': {
      id: '/api/liquidium/auth'
      path: '/api/liquidium/auth'
      fullPath: '/api/liquidium/auth'
      preLoaderRoute: typeof ApiLiquidiumAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/liquidium/challenge': {
      id: '/api/liquidium/challenge'
      path: '/api/liquidium/challenge'
      fullPath: '/api/liquidium/challenge'
      preLoaderRoute: typeof ApiLiquidiumChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/liquidium/portfolio': {
      id: '/api/liquidium/portfolio'
      path: '/api/liquidium/portfolio'
      fullPath: '/api/liquidium/portfolio'
      preLoaderRoute: typeof ApiLiquidiumPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/liquidium/repay': {
      id: '/api/liquidium/repay'
      path: '/api/liquidium/repay'
      fullPath: '/api/liquidium/repay'
      preLoaderRoute: typeof ApiLiquidiumRepayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ordiscan/btc-balance': {
      id: '/api/ordiscan/btc-balance'
      path: '/api/ordiscan/btc-balance'
      fullPath: '/api/ordiscan/btc-balance'
      preLoaderRoute: typeof ApiOrdiscanBtcBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ordiscan/list-runes': {
      id: '/api/ordiscan/list-runes'
      path: '/api/ordiscan/list-runes'
      fullPath: '/api/ordiscan/list-runes'
      preLoaderRoute: typeof ApiOrdiscanListRunesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ordiscan/rune-activity': {
      id: '/api/ordiscan/rune-activity'
      path: '/api/ordiscan/rune-activity'
      fullPath: '/api/ordiscan/rune-activity'
      preLoaderRoute: typeof ApiOrdiscanRuneActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ordiscan/rune-balances': {
      id: '/api/ordiscan/rune-balances'
      path: '/api/ordiscan/rune-balances'
      fullPath: '/api/ordiscan/rune-balances'
      preLoaderRoute: typeof ApiOrdiscanRuneBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ordiscan/rune-info': {
      id: '/api/ordiscan/rune-info'
      path: '/api/ordiscan/rune-info'
      fullPath: '/api/ordiscan/rune-info'
      preLoaderRoute: typeof ApiOrdiscanRuneInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ordiscan/rune-info-by-id': {
      id: '/api/ordiscan/rune-info-by-id'
      path: '/api/ordiscan/rune-info-by-id'
      fullPath: '/api/ordiscan/rune-info-by-id'
      preLoaderRoute: typeof ApiOrdiscanRuneInfoByIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ordiscan/rune-market': {
      id: '/api/ordiscan/rune-market'
      path: '/api/ordiscan/rune-market'
      fullPath: '/api/ordiscan/rune-market'
      preLoaderRoute: typeof ApiOrdiscanRuneMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ordiscan/rune-update': {
      id: '/api/ordiscan/rune-update'
      path: '/api/ordiscan/rune-update'
      fullPath: '/api/ordiscan/rune-update'
      preLoaderRoute: typeof ApiOrdiscanRuneUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sats-terminal/quote': {
      id: '/api/sats-terminal/quote'
      path: '/api/sats-terminal/quote'
      fullPath: '/api/sats-terminal/quote'
      preLoaderRoute: typeof ApiSatsTerminalQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sats-terminal/search': {
      id: '/api/sats-terminal/search'
      path: '/api/sats-terminal/search'
      fullPath: '/api/sats-terminal/search'
      preLoaderRoute: typeof ApiSatsTerminalSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/liquidium/borrow/prepare': {
      id: '/api/liquidium/borrow/prepare'
      path: '/api/liquidium/borrow/prepare'
      fullPath: '/api/liquidium/borrow/prepare'
      preLoaderRoute: typeof ApiLiquidiumBorrowPrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/liquidium/borrow/quotes': {
      id: '/api/liquidium/borrow/quotes'
      path: '/api/liquidium/borrow/quotes'
      fullPath: '/api/liquidium/borrow/quotes'
      preLoaderRoute: typeof ApiLiquidiumBorrowQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/liquidium/borrow/ranges': {
      id: '/api/liquidium/borrow/ranges'
      path: '/api/liquidium/borrow/ranges'
      fullPath: '/api/liquidium/borrow/ranges'
      preLoaderRoute: typeof ApiLiquidiumBorrowRangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/liquidium/borrow/submit': {
      id: '/api/liquidium/borrow/submit'
      path: '/api/liquidium/borrow/submit'
      fullPath: '/api/liquidium/borrow/submit'
      preLoaderRoute: typeof ApiLiquidiumBorrowSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sats-terminal/psbt/confirm': {
      id: '/api/sats-terminal/psbt/confirm'
      path: '/api/sats-terminal/psbt/confirm'
      fullPath: '/api/sats-terminal/psbt/confirm'
      preLoaderRoute: typeof ApiSatsTerminalPsbtConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sats-terminal/psbt/create': {
      id: '/api/sats-terminal/psbt/create'
      path: '/api/sats-terminal/psbt/create'
      fullPath: '/api/sats-terminal/psbt/create'
      preLoaderRoute: typeof ApiSatsTerminalPsbtCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BorrowRoute: BorrowRoute,
  ChangelogRoute: ChangelogRoute,
  DocsRoute: DocsRoute,
  LegalRoute: LegalRoute,
  PortfolioRoute: PortfolioRoute,
  RunesInfoRoute: RunesInfoRoute,
  SwapRoute: SwapRoute,
  YourTxsRoute: YourTxsRoute,
  ApiBtcPriceRoute: ApiBtcPriceRoute,
  ApiPopularRunesRoute: ApiPopularRunesRoute,
  ApiPortfolioDataRoute: ApiPortfolioDataRoute,
  ApiRunePriceHistoryRoute: ApiRunePriceHistoryRoute,
  ApiLiquidiumAuthRoute: ApiLiquidiumAuthRoute,
  ApiLiquidiumChallengeRoute: ApiLiquidiumChallengeRoute,
  ApiLiquidiumPortfolioRoute: ApiLiquidiumPortfolioRoute,
  ApiLiquidiumRepayRoute: ApiLiquidiumRepayRoute,
  ApiOrdiscanBtcBalanceRoute: ApiOrdiscanBtcBalanceRoute,
  ApiOrdiscanListRunesRoute: ApiOrdiscanListRunesRoute,
  ApiOrdiscanRuneActivityRoute: ApiOrdiscanRuneActivityRoute,
  ApiOrdiscanRuneBalancesRoute: ApiOrdiscanRuneBalancesRoute,
  ApiOrdiscanRuneInfoRoute: ApiOrdiscanRuneInfoRoute,
  ApiOrdiscanRuneInfoByIdRoute: ApiOrdiscanRuneInfoByIdRoute,
  ApiOrdiscanRuneMarketRoute: ApiOrdiscanRuneMarketRoute,
  ApiOrdiscanRuneUpdateRoute: ApiOrdiscanRuneUpdateRoute,
  ApiSatsTerminalQuoteRoute: ApiSatsTerminalQuoteRoute,
  ApiSatsTerminalSearchRoute: ApiSatsTerminalSearchRoute,
  ApiLiquidiumBorrowPrepareRoute: ApiLiquidiumBorrowPrepareRoute,
  ApiLiquidiumBorrowQuotesRoute: ApiLiquidiumBorrowQuotesRoute,
  ApiLiquidiumBorrowRangesRoute: ApiLiquidiumBorrowRangesRoute,
  ApiLiquidiumBorrowSubmitRoute: ApiLiquidiumBorrowSubmitRoute,
  ApiSatsTerminalPsbtConfirmRoute: ApiSatsTerminalPsbtConfirmRoute,
  ApiSatsTerminalPsbtCreateRoute: ApiSatsTerminalPsbtCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
